Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('category-list/',views.category_list),
    path('category-detail/<int:id>/',views.category_detail),
    path('post-list/',views.post_list),
    path('post-detail/<int:id>/',views.post_detail),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_category/', views.create_category, name='create_category'),
    path('list_category/', views.list_category, name='list_category'),
    path('detail_category/<int:id>/', views.detail_category, name='detail_category'),
    path('edit_category/<int:id>/', views.edit_category, name = 'edit_category'),
    path('delete_category/<int:id>/', views.delete_category, name='delete_category'),
    path('create_region/', views.create_region, name='create_region'),
    path('list_region/', views.list_region, name='list_region'),
    path('detail_region/<int:id>/', views.detail_region, name='detail_region'),
    path('edit_region/<int:id>/', views.edit_region, name = 'edit_region'),
    path('delete_region/<int:id>/', views.delete_region, name='delete_region'),
    path('create_post/', views.create_post, name='create_post'),
    path('list_post/', views.list_post, name='list_post'),
    path('detail_post/<int:id>/', views.detail_post, name='detail_post'),
    path('edit_post/<int:id>/', views.edit_post, name = 'edit_post'),
    path('delete_post/<int:id>/', views.delete_post, name='delete_post'),
    path('list_contact/', views.list_contact, name='list_contact'),
    path('detail_contact/<int:id>/', views.detail_contact, name='detail_contact'),
    path('edit_contact/<int:id>/', views.edit_contact, name = 'edit_contact'),
    path('register/', views.register, name='register'),
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),
    ]

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from main import models
from django.contrib import messages
from django.db.models import Q



@login_required(login_url='dashboard:log_in')
def index(request):
    categories = models.Category.objects.all()
    user = User.objects.last()
    context = {
        'categories': categories,
        'user': user,
    }
    return render(request, 'dashboard/index.html', context)



"""here has written about region"""

@login_required(login_url='dashboard:log_in')
def create_region(request):
    if request.method == "POST":
        try:
            name = request.POST['name']
            models.Region.objects.create(name=name)
            messages.success(request, 'Region created succesfully')
        except:
            messages.error(request, 'Something getting wrong')
    return render(request, 'dashboard/region/create.html')



@login_required(login_url='dashboard:log_in')
def list_region(request):
    regions = models.Region.objects.all()
    context = {'regions':regions}
    return render(request, 'dashboard/region/list.html', context)


def detail_region(request, id):
    region = models.Region.objects.get(id=id)
    context = {'region':region}
    return render(request, 'dashboard/region/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_region(request, id):
    region = models.region.objects.get(id=id)
    if request.method =='POST':
        try:
            region.name = request.POST['name']
            region.save()
            messages.success(request, 'Region updated succesfully')
        except:
            messages.error(request, 'Something getting wrong')
        return redirect('dashboard:region_detail', region.id)
    context = {'region':region}
    return render(request, 'dashboard/region/edit.html', context)


def delete_region(request, id):
    try:
        models.Region.objects.get(id=id).delete()
        messages.error(request, 'Region deleted')
    except:
        messages.error(request, 'Something getting wrong')
    return redirect('dashboard:region_list')



"""Here has written about category"""

@login_required(login_url='dashboard:log_in')
def create_category(request):
    if request.method == "POST":
        try:
            name = request.POST['name']
            models.Category.objects.create(name=name,)
            messages.success(request, 'categoriya created succesfully')
        except:
            messages.error(request, 'Something getting wrong')
    return render(request, 'dashboard/category/create.html')


@login_required(login_url='dashboard:log_in')
def list_category(request):
    categories = models.Category.objects.all()
    context = {'categories':categories}
    return render(request, 'dashboard/category/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_category(request, id):
    category = models.Category.objects.get(id=id)
    context = {'category':category}
    return render(request, 'dashboard/category/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_category(request, id):
    category = models.category.objects.get(id=id)
    if request.method =='POST':
        try:
            category.name = request.POST['name']
            category.save()
            messages.success(request, 'categoriya updated succesfully')
        except:
            messages.error(request, 'Something getting wrong')

        return redirect('dashboard:category_list', category.id)
    context = {'category':category}
    return render(request, 'dashboard/category/edit.html', context)


@login_required(login_url='dashboard:log_in')
def delete_category(request, id):
    try:
        models.Category.objects.get(id=id).delete()
        messages.error(request, 'c')
    except:
        messages.error(request, 'Something getting wrong')
    return redirect('dashboard:category_list')


""" Here has written about posts"""

@login_required(login_url='dashboard:log_in')
def create_post(request):
    users = models.User.objects.all()
    categories = models.Category.objects.all()
    regions = models.Region.objects.all()
    context = {
        'users':users,
        'categories':categories,
        'regions':regions
    }
    if request.method == 'POST':
       
            title = request.POST['title']
            body = request.POST['body']
            banner_img = request.FILES['banner_img']
            date = request.POST['date']
            user_id = request.POST['user_id']
            category_id = request.POST['category_id']
            region_id = request.POST['region_id']
            user = models.User.objects.get(id=user_id)
            category = models.Category.objects.get(id=category_id)
            region = models.Region.objects.get(id=region_id)
            post = models.Post.objects.create(
                title=title,
                body=body,
                banner_img=banner_img,
                date=date,
                user=user,
                region=region,
                category=category
                )

    return render(request, 'dashboard/post/create.html', context)


@login_required(login_url='dashboard:log_in')
def list_post(request):
    posts = models.Post.objects.all()
    context = {'posts': posts}
    return render(request, 'dashboard/post/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_post(request, id):
    post = models.Post.objects.get(id=id)
    context = {'post': post}
    return render(request, 'dashboard/post/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_post(request, id):
    post = models.Post.objects.get(id=id)
    if request.method == 'POST':
        try:
            title = request.POST.get('title')
            body = request.POST.get('body')
            banner_img = request.POST.get('banner_img')
            date = request.POST.get('date')
            author = request.POST.get('author')
            category = request.POST.get('category')
            region = request.POST.get('region')
            models.Post.objects.filter(id=id).update(
                title=title,
                body=body,
                banner_img=banner_img,
                date=date,
                author=author,
                category=category,
                region=region
            )
            messages.success(request, 'post updated succesfully')
            return redirect('dashboard:detail_post', post.id)
        except:
            messages.error(request, 'Something getting wrong')

    return render(request, 'dashboard/post/edit.html', context={'post': post})


@login_required(login_url='dashboard:log_in')
def delete_post(request, id):
    try:
        models.Post.objects.filter(id=id).delete()
        messages.success(request, 'post deleted succesfully')
        return redirect('dashboard:list_post')
    except:
        messages.error(request, 'Something getting wrong')
    return render(request, 'dashboard/post/list.html')



"""Here has written about contact"""

@login_required(login_url='dashboard:log_in')
def list_contact(request):   
    contacts = models.Contact.objects.all()
    context = {'contacts':contacts}
    return render(request, 'dashboard/contact/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_contact(request, id):
    contacts = models.Contact.objects.get(id=id) 
    context = {'contacts':contacts}
    return render(request, 'dashboard/contact/detail.html', context)

@login_required(login_url='dashboard:log_in')
def edit_contact(request, id):
    contact = models.Contact.objects.get(id=id)
    if request.method == "POST":
        try:
            is_show = request.POST.get('is_show')  
            contact.is_show = is_show == 'on'
            contact.save()
            messages.success(request, 'information of contact updated succesfully')
        except:
            messages.error(request, 'Something getting wrong')
        return redirect('dashboard:contact_list')
    context = {'contact': contact}
    return render(request, 'dashboard/contact/edit.html', context)



""" Here has written about register, login and logout"""


def register(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            password_confirm = request.POST['password_confirm']
            if password == password_confirm:
                User.objects.create_user(
                    username=username,
                    password=password
                )
            messages.success(request, 'username created succesfully')
        except:
            messages.error(request, 'Something getting wrong')
            return redirect('dashboard:index')
    return render(request, 'dashboard/auth/register.html')


def log_in(request):
    if request.method == 'POST':
        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            messages.success(request, 'You are welcome!')
        except:
            messages.error(request, 'Something getting wrong')
        if user is not None:
            login(request, user)
            return redirect('dashboard:index')
        else:
            return render(request, 'dashboard/auth/login.html', {'error_message': 'Invalid username or password.'})
    else:
        return render(request, 'dashboard/auth/login.html')


def log_out(request):
    logout(request)
    return redirect('main:index')


def query(request):
    q = request.GET['q']
    posts = models.Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    region = models.Region.objects.filter(Q(name__icontains=q))

templates/dashboard/category/create.html
{% extends 'dashboard/base.html' %}
{% block content %}
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title">Categoriya</h4>
                                        <p class="text-muted font-14">
                              
                                        </p>

                                        <div class="tab-content">
                                            <div class="tab-pane active show" id="typeahead-preview" role="tabpanel">
                                                <div class="row">
                                                    <form method="post">
                                                        {% csrf_token %}
                                                        <div class="col-12">
                                                            <div class="mb-3">
                                                                <label class="form-label">Kategoriya nomi </label>
                                                                <span class="twitter-typeahead" style="position: relative; display: inline-block;"><input type="text" class="form-control tt-hint" data-provide="typeahead" readonly="" autocomplete="off" spellcheck="false" tabindex="-1" dir="ltr" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box padding-box rgb(255, 255, 255);"><input type="text" class="form-control tt-input" data-provide="typeahead" id="the-basics" placeholder="categoriya nomi..." name="name" autocomplete="off" spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;"><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: Nunito, sans-serif; font-size: 14.4px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div class="tt-dataset tt-dataset-states"></div></div></span>
                                                            </div>
                                            
                                                        </div> <!-- end col -->
                                                        
                                                        <button type="submit" class="btn btn-outline-success"><i class="uil-upload"></i> Yaratish</button>
                                                    </form>
                                                </div>
                                                <!-- end row -->                      
                                            </div> <!-- end preview-->
                            
                                        </div> <!-- end tab-content-->

                                    </div> <!-- end card-body -->
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                        </div>

                        <!-- end row -->

                    </div>
                    <!-- container -->

                </div>
                <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                            </div>
                            <div class="col-md-6">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">About</a>
                                    <a href="javascript: void(0);">Support</a>
                                    <a href="javascript: void(0);">Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>

{% endblock %}

templates/dashboard/category/detail.html
{% extends 'dashboard/base.html' %}
{% block content %}
    
    <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <div class="d-flex justify-content-evenly align-items-center">
                                        <h4 class="page-title" style="display: inline;">Detail</h4>
                                        <a href="{% url 'dashboard:edit_category' category.id %}" class="btn btn-outline-primary">O`zgartirish</a>
                                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#centermodal">O`chirish</button>
                                        <div class="modal fade" id="centermodal" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title" id="myCenterModalLabel">Kategoriyani  o`chirmoqchimisiz? </h4>
                                                        <form method="get" action="{% url 'dashboard:delete_category' category.id %}">
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            
                                                            <input type="checkbox" class="form-check-input" id="customCheckcolor7" required>
                                                            <label for="chkb">Ha</label> <br> <br>
                                                            <button type="button" class="btn btn-dark" data-bs-dismiss="modal" aria-hidden="true">Qaytish</button>
                                                            <button class="btn btn-danger" type="submit">O`chirish</button>
                                                        </div>
                                                        </form>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
    
                                                
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                <div class="card-body">
                                    <h4 class="header-title mb-3">Category haqida batafsil</h4>
        
                                    <div class="table-responsive">
                                        <table class="table mb-0">
                                        
                                            <tbody>
                                                <tr>
                                                    <td><b>ID :</b></td>
                                                    <td>{{category.id}}</td>
                                                </tr>
                                            <tr>
                                                <td><b>Nom :</b></td>
                                                <td>{{category.name}}</td>
                                            </tr>
                                        
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- end table-responsive -->
        
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- container -->

                </div>
                <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                            </div>
                            <div class="col-md-6">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">About</a>
                                    <a href="javascript: void(0);">Support</a>
                                    <a href="javascript: void(0);">Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>
{% endblock %}

templates/dashboard/category/list.html
{% extends 'dashboard/base.html' %}
{% block content %}
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-6">
                                <h4 class="header-title">Kategoryalar ro'yxati</h4>
                                <table class="table table-striped table-centered mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nom</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for category in categories %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{category.name}}</td>
                                        <td class="table-action">
                                            <a href="{% url 'dashboard:detail_category' category.id %}" class="action-icon"> <i class=" ri-share-forward-2-line"></i></a>    
                                            <a href="{% url 'dashboard:edit_category' category.id %}" class="action-icon"><i class=" uil-pen"></i></a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- container -->

                </div>
                <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                            </div>
                            <div class="col-md-6">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">About</a>
                                    <a href="javascript: void(0);">Support</a>
                                    <a href="javascript: void(0);">Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>
{% endblock %}