Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('category-list/',views.category_list),
    path('category-detail/<int:id>/',views.category_detail),
    path('post-list/',views.post_list),
    path('post-detail/<int:id>/',views.post_detail),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('category/', views.categories, name='categories'),
    path('post/', views.posts, name='post'),
]

templates/front/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>The Latest News</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'front/img/core-img/favicon.ico' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'front/style.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- Header Area Start -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="newsbox-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container-fluid">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="newsboxNav">
                        <!-- Nav brand -->
                        <a href="{% url 'main:index' %}" class="nav-brand"><img src="{% static 'front/img/box.jpg' %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Navbar Start -->
                            <div class="classynav">
                                <ul>
                                    <li ><a href="{% url 'main:index' %}" style="font-size: 20px;">Home</a>
                                    </li>
                                    <li><a href="{% url 'main:post' %}" style="font-size: 20px;">News</a>
                                    </li>
                                    <li><a href="{% url 'main:contact' %}" style="font-size: 20px;">Contact</a>
                                    </li>
                                    <li><a href="{% url 'main:categories' %}" style="font-size: 20px;">categories</a>
                                        
                                    </li>
                                </ul>
                            </div><!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->

    <!-- Breaking News Area Start -->
    <section class="breaking-news-area clearfix">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- Breaking News Widget -->
                    <div class="breaking-news-ticker d-flex flex-wrap align-items-center">
                        <div class="title">
                            <h6>Latest news</h6>
                        </div>
                        <div id="breakingNewsTicker" class="ticker">
                            <ul >
                                {% for post in posts %}
                                    <li><a style="font-size: 25px;" href="#">{{post.title}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breaking News Area End -->

    {% block content %}
    {% endblock %}

    <!-- Footer Area Start -->
    <footer class="footer-area">
        <!-- Footer Logo -->
        <div class="footer-logo mb-100">
            <a href="{% url 'main:index' %}"><img src="{% static 'front/img/box.jpg' %}" alt=""></a>
        </div>
        <!-- Footer Content -->
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-content text-center">
                        <!-- Footer Nav -->
                        <div class="footer-nav">
                            <ul>
                                <li><a href="{% url 'main:index' %}">Home</a></li>
                                <li><a href="{% url 'main:contact' %}">Contact</a></li>
                                <li><a href="{% url 'main:post' %}">Post</a></li>
                            </ul>
                        </div>
                        <!-- Social Info -->
                        <div class="footer-social-info">
                            <a href="https://github.com/TojiboyevAzizbek" data-toggle="tooltip" target="_blank" data-placement="top" title="Git Hub"><i class="fa fa-github" aria-hidden="true"></i></a>
                            <a href="https://t.me/tojiboyevdev" target="_blank" data-toggle="tooltip" data-placement="top" title="Telegram"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                            <a href="https://instagram.com/tojiboyevdev" target="_blank" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'front/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'front/js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'front/js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'front/js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'front/js/active.js' %}"></script>
</body>

</html>

templates/front/category.html
{% extends "front/base.html" %}
{% load static %}
{% block content %}

<!-- Catagory Featured Area Start -->
<div class="catagory-featured-post bg-overlay clearfix" style="background-image: url({% static 'front/img/ring.jpg' %})">
    <div class="container-fluid h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 col-lg-9">
                <!-- Post Content -->
                <div class="post-content">
                    <p class="tag"><span>News</span></p>
                    <p style="font-size: 40px;">You can find the latest news in our website</p>
                </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Catagory Featured Area End -->
    
    <!-- Intro News Area Start -->
    <section class="intro-news-area section-padding-100-0 mb-70">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Intro News Tabs Area -->
                <div class="col-12 col-lg-8">
                    <div class="intro-news-tab">

                        <!-- Intro News Filter -->
                        <div class="intro-news-filter d-flex justify-content-between">
                            <h6>All news</h6>
                            <nav>
                                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                    <a class="nav-item nav-link active" id="nav1" data-toggle="tab" href="#nav-1" role="tab" aria-controls="nav-1" aria-selected="true">Latest news</a>
                                    <a class="nav-item nav-link" id="nav2" data-toggle="tab" href="#nav-2" role="tab" aria-controls="nav-2" aria-selected="false">Popular</a>
                                    <a class="nav-item nav-link" id="nav3" data-toggle="tab" href="#nav-3" role="tab" aria-controls="nav-3" aria-selected="false">International</a>
                                    <a class="nav-item nav-link" id="nav4" data-toggle="tab" href="#nav-4" role="tab" aria-controls="nav-4" aria-selected="false">Local</a>
                                </div>
                            </nav>
                        </div>

                        <div class="tab-content" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="nav-1" role="tabpanel" aria-labelledby="nav1">
                                <div class="row">
                                    <!-- Single News Area -->
                                    <div class="col-20" >
                                        <div class="single-blog-post style-2 mb-5" >
                                            <!-- Blog Thumbnail -->
                                            <div class="blog-thumbnail" >
                                                <a href="#"><img style="width: 1000px; height: 500px;" src="{% static 'front/img/isroil.jpg' %}" alt=""></a>
                                            </div>

                                            <!-- Blog Content -->
                                            <div class="blog-content">
                                                <span class="post-date">March 24, 2024</span>
                                                <a href="#" class="post-title">Israil Madrimov</a>
                                                <a href="#" class="post-author mb-30">By Tojiboyev Azizbek</a>
                                                <p>Israil Madrimov (Cyrillic: Исраил Мадримов) is a professional boxer from Uzbekistan, who has held WBA super welterweight title since March 2024. As an amateur, he won a silver medal in the welterweight division at the 2014 Asian Games and gold in the middleweight division at the 2018 edition. </p>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Single News Area -->
                                    <div class="col-12 col-sm-12">
                                        <div class="single-blog-post style-2 mb-5">
                                            <!-- Blog Thumbnail -->
                                            <div class="blog-thumbnail">
                                                <a href="#"><img src="{% static 'front/img/murod.jpg' %}" alt=""></a>
                                            </div>

                                            <div class="blog-content">
                                                <span class="post-date">March 24, 2024</span>
                                                <a href="#" class="post-title">Murodjon Akhmadaliyev</a>
                                                <a href="#" class="post-author mb-30" > By Tojiboyev Azizbek</a>
                                                    <p>Murodjon Kakharovich Akhmadaliev (Uzbek: Murodjon Qahhorovich Ahmadaliyev; born 2 November 1994) is an Uzbekistani professional boxer. He is a former unified super-bantamweight champion, having held the WBA (Super), and IBF titles between 2020 and 2023.[2] As an amateur, he won a silver medal at the 2015 World Championships and a bronze at the 2016 Olympics as a bantamweight.[3] As of April 2021, he is ranked as the world's best active super-bantamweight by The Ring,[4] fourth by BoxRec[5] and second best by the Transnational Boxing Rankings Board. </p>
                                            </div>
                                        </div>
                                    </div>

                                            <!-- Blog Content -->
                                            

                                    <!-- Single News Area -->
                                    <div class="col-12 col-sm-12">
                                        <div class="single-blog-post style-2 mb-5">
                                            <!-- Blog Thumbnail -->
                                            <div class="blog-thumbnail">
                                                <a href="#"><img src="{% static 'front/img/shox.jpg' %}" alt=""></a>
                                            </div>

                                            <!-- Blog Content -->
                                            <div class="blog-content">
                                                <span class="post-date">March 24, 2024</span>
                                                <a href="#" class="post-title">Shohjahon Ergashev</a>
                                                <a href="#" class="post-author mb-30" > By Tojiboyev Azizbek</a>
                                                    <p>Ergashev fought 9 professional fights, all of which ended before stoppage time, in Russia and then signed up for Salita promotions and subsequently moved to the US.[2] In the US he had 2 successful fights against Marquis Hawthorne and Sonny Fredrickson where, he won both fights via technical knockout. </p>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Single News Area -->
                                    <div class="col-12 col-sm-12">
                                        <div class="single-blog-post style-2 mb-5">
                                            <!-- Blog Thumbnail -->
                                            <div class="blog-thumbnail">
                                                <a href="#"><img src="{% static 'front/img/shax.jpg' %}" alt=""></a>
                                            </div>

                                            <!-- Blog Content -->
                                            <div class="blog-content">
                                                <span class="post-date">March 24, 2024</span>
                                                <a href="#" class="post-title">Shahram giyasov</a>
                                                <a href="#" class="post-author mb-30" > By Tojiboyev Azizbek</a>
                                                    <p>On 10 March 2018, Giyasov made his professional debut against Nicolas Atilio Velazquez of Argentina. Giyasov won the fight after knocking Velazquez out with a left hook to the body within the first minute of the opening round. </p>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Single News Area -->
                                    <div class="col-12 col-sm-12">
                                        <div class="single-blog-post style-2 mb-5">
                                            <!-- Blog Thumbnail -->
                                            <div class="blog-thumbnail">
                                                <a href="#"><img src="{% static 'front/img/boh.jpg' %}" alt=""></a>
                                            </div>

                                            <!-- Blog Content -->
                                            <div class="blog-content">
                                                <span class="post-date">March 24, 2024</span>
                                                <a href="#" class="post-title">Bahodir Jalolov</a>
                                                <a href="#" class="post-author mb-30" > By Tojiboyev Azizbek</a>
                                                    <p>Bakhodir Jalolov (Uzbek: Bahodir Jalolov) is an Uzbekistani professional boxer who won a bronze medal at the 2015 World Championships, and gold at the 2019 and 2023 World Championships and 2020 Summer Olympics. He also competed at the 2016 Summer Olympics, and acted as Uzbekistan's flag bearer at both games. </p>
                                            </div>
                                        </div>
                                    </div>

                           

                                    <!-- Single News Area -->
                                    
                
                <!-- Sidebar Widget -->
                <div class="col-12 col-sm-9 col-md-6 col-lg-4">
                    <div class="sidebar-area">

                        <!-- Latest News Widget -->
                        

                            <!-- Single News Area -->
                            <div class="single-blog-post d-flex style-4 mb-30">
                                <!-- Blog Thumbnail -->
                             

                                <!-- Blog Content -->
                             

                            <!-- Single News Area -->
                            <div class="single-blog-post d-flex style-4 mb-30">
                                <!-- Blog Thumbnail -->
                           

                            <!-- Single News Area -->
                            <div class="single-blog-post d-flex style-4 mb-30">
                                <!-- Blog Thumbnail -->
                              

                            <!-- Single News Area -->
                            <div class="single-blog-post d-flex style-4 mb-30">
                                <!-- Blog Thumbnail -->
                              

                                <!-- Blog Content -->
                              

                            <!-- Single News Area -->
                            <div class="single-blog-post d-flex style-4 mb-30">
                                <!-- Blog Thumbnail -->
                               

                                <!-- Blog Content -->
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Intro News Area End ##### -->
    
{% endblock %}

templates/front/contact.html
{% extends "front/base.html" %}
{% load static %}
{% block content %}

<!-- Contact Area Start -->
<div class="hero-contact-area bg-overlay clearfix" style="background-image: url({% static 'front/img/gym.jpg' %})">
    <div class="container-fluid h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 col-lg-7">
                <div class="post-content">
                    <p class="tag"><span>Login</span></p>
                        <p class="post-title">You can find the latest news in our</p>
                        <div class="d-flex align-items-center">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Area End -->

    <!-- Contact Area Start -->
    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">

                <div class="col-12 col-lg-8">
                    <div class="contact-content mb-100">
                        
                        <!-- Logo -->
                        <a href="#" class="d-block mb-50"><img src="{% static 'front/img/core-img/logo.png' %}" alt=""></a>
                        
                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-15">
                                <img src="{% static 'front/img/core-img/map-pin.png' %}" alt="">
                            </div>
                            <p>Uzbekistan</p>
                        </div>
                        
                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-15">
                                <img src="{% static 'front/img/core-img/smartphone.png' %}" alt="">
                            </div>
                            <p>+998908348830</p>
                        </div>

                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-15">
                                <img src="{% static 'front/img/core-img/paper-plane.png' %}" alt="">
                            </div>
                            <p>tojiboyev170@gmail.com</p>
                        </div>

                        <!-- Contact Social Info -->
                        <div class="contact-social-info mt-50 mb-70">
                            <a href="https://github.com/TojiboyevAzizbek" data-toggle="tooltip" target="_blank" data-placement="top" title="Git Hub"><i class="fa fa-github" aria-hidden="true"></i></a>
                            <a href="https://t.me/tojiboyevdev" target="_blank" data-toggle="tooltip" data-placement="top" title="Telegram"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                            <a href="https://instagram.com/tojiboyevdev" target="_blank" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </div>

                        <!-- Contact Form Area -->
                        <div class="contact-form-area mb-70">
                            <h4 class="mb-50">Get In Touch</h4>
                            <form method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="name" placeholder="Name" name="name" style="background-color: lightskyblue;">
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="subject" placeholder="Phone number" name="phone" style="background-color: lightskyblue;">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <input type="email" class="form-control" id="email" placeholder="Email" name="email" style="background-color: lightskyblue;">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <textarea name="message" class="form-control" id="message" cols="30" rows="10" placeholder="Message" style="background-color: lightskyblue;"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12" style="display: flex; justify-content: center;">
                                        <button class="btn newsbox-btn mt-30" type="submit">Send</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                       

{% endblock %}

templates/front/index.html
{% extends "front/base.html" %}
{% load static %}
{% block content %}

    <!-- ##### Top News Area Start ##### -->
    <div class="top-news-area section-padding-100">
        <div class="container">
            <div class="row">
                {% for post in posts %}
                <!-- Single News Area -->
                <div class="col-12 col-sm-12 col-lg-12">
                    <div class="single-blog-post style-2 mb-5">
                        <!-- Blog Thumbnail -->
                        <div class="blog-thumbnail"  style="width: 1200px;" >
                            <a href="#"  style="width: 1000px;" ><img style="height: 700px;"src="{{post.banner_img.url}}" alt=""></a>
                        </div>

                        <!-- Blog Content -->
                        <div class="blog-content">
                            <span class="post-date">{{post.date}}</span>
                            <a href="#" class="post-title">{{post.title}}</a>
                            <a href="#" class="post-author">By {{post.author}}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="col-12">
                    <div class="load-more-button text-center">
                        <a href="" class="btn newsbox-btn">Load More</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- ##### Top News Area End ##### -->

{% endblock %}

templates/front/post.html
{% extends "front/base.html" %}
{% load static %}
{% block content %}

    <!-- Post Details Title Area Start -->
    <div class="post-details-title-area bg-overlay clearfix" style="background-image: url({% static 'front/img/back.jpg' %})">
        <div class="container-fluid h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 col-lg-8">
                    <!-- Post Content -->
                    <div class="post-content">
                        <p class="tag" ><span >The latest news</span></p>
                        <p class="post-title">You can find the latest news in our</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Post Details Title Area End -->

    <!-- Post Details Area Start -->
    <section class="post-news-area section-padding-100-0 mb-70">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Post Details Content Area -->
                <div class="col-12 col-lg-8">

                    <!-- Comment Area Start -->
                    <div class="comment_area clearfix mb-100">
                        <h4 class="mb-50">Comments</h4>

                        <ol>
                            {% for comment in comments %}
                            <!-- Single Comment Area -->
                            <li class="single_comment_area">
                                <!-- Comment Content -->
                                <div class="comment-content d-flex">
                                    <!-- Comment Author -->
                                    <div class="comment-author">
                                        <img src="{% static 'front/img/bg-img/1.jpg' %}" alt="author">
                                    </div>
                                    <!-- Comment Meta -->
                                    <div class="comment-meta">
                                        <div class="d-flex">
                                            <a href="#" class="post-date">{{comment.date}}</a>
                                            <a href="#" class="reply">{{comment.post}}</a>
                                        </div>
                                        <p>{{comment.text}}.</p>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>

                <!-- Sidebar Widget -->
                <div class="col-12 col-sm-9 col-md-6 col-lg-4">
                    <div class="sidebar-area">

                        <!-- Latest News Widget -->
                        <div class="single-widget-area news-widget mb-30">
                            <h4>Latest News</h4>
                            {% for post in posts %}
                            <!-- Single News Area -->
                            <div class="single-blog-post d-flex style-4 mb-30">
                                <!-- Blog Thumbnail -->
                                <div class="blog-thumbnail">
                                    <a href="#"><img src="{{post.banner_img.url}}" alt=""></a>
                                </div>

                                <!-- Blog Content -->
                                <div class="blog-content">
                                    <span class="post-date">{{post.date}}</span>
                                    <a href="#" class="post-title">{{post.title}}</a>
                                </div>
                            </div>
                            {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Post Details Area End ##### -->
{% endblock %}